version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend
    links:
      - redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CONFIG_PATH=./config/config.yaml
    env_file:
      - .env

  redis:
    image: redis:7.2.4-alpine
    restart: always
    container_name: redis
    env_file:
      - .env
    networks:
      - redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - data:/var/lib/redis/data
      - redis.conf:/var/lib/redis/redis.conf
    ports:
      - "6379:6379"
volumes:
  data:
  redis.conf:
networks:
  redis:
